remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: Swetha Ashok
logo: /images/fa25_headshot.JPG
description: >
  Electrical Engineering & Computer Science at UC Berkeley 
show_downloads: true
theme: jekyll-theme-minimal
